// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    account_geography: {
        name: "account_geography";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType BIGINT */
          projects: number;
          /** @sqlType BIGINT */
          value_eur: number;
          /** @sqlType BIGINT */
          at_risk_modules: number;
        }>;
      };
    account_kpis: {
        name: "account_kpis";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          projects: number;
          /** @sqlType BIGINT */
          countries: number;
          /** @sqlType BIGINT */
          modules: number;
          /** @sqlType BIGINT */
          total_value_eur: number;
          /** @sqlType BIGINT */
          t9_count: number;
          /** @sqlType BIGINT */
          t4_t6_count: number;
          /** @sqlType BIGINT */
          exception_count: number;
          /** @sqlType BIGINT */
          fastpick_projects: number;
          /** @sqlType BIGINT */
          storepick_projects: number;
          /** @sqlType DATE */
          first_contract: string;
          /** @sqlType DATE */
          latest_contract: string;
        }>;
      };
    account_modules: {
        name: "account_modules";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType BIGINT */
          sale_lines: number;
          /** @sqlType BIGINT */
          units: number;
          /** @sqlType BIGINT */
          value_eur: number;
          /** @sqlType STRING */
          risk_status: string;
        }>;
      };
    account_projects: {
        name: "account_projects";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          project_status: string;
          /** @sqlType STRING */
          project_size_category: string;
          /** @sqlType DATE */
          contract_date: string;
          /** @sqlType DOUBLE */
          project_value_eur: number;
          /** @sqlType BIGINT */
          modules: number;
          /** @sqlType BIGINT */
          t9_modules: number;
          /** @sqlType BIGINT */
          t4_t6_modules: number;
          /** @sqlType BIGINT */
          exception_modules: number;
        }>;
      };
    account_risks: {
        name: "account_risks";
        parameters: {
          /** STRING - use sql.string() */
          customer: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          quantity: number;
          /** @sqlType BIGINT */
          sales_value_eur: number;
          /** @sqlType DATE */
          sales_date: string;
          /** @sqlType STRING */
          risk_type: string;
        }>;
      };
    accounts_multi: {
        name: "accounts_multi";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType BIGINT */
          projects: number;
          /** @sqlType BIGINT */
          countries: number;
          /** @sqlType BIGINT */
          total_value_eur: number;
          /** @sqlType BIGINT */
          at_risk_modules: number;
        }>;
      };
    compliance_by_family: {
        name: "compliance_by_family";
        parameters: {
          /** STRING - use sql.string() */
          solution: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          exception_modules: number;
          /** @sqlType BIGINT */
          total_modules: number;
          /** @sqlType DECIMAL(27,2) */
          exception_rate: number;
          /** @sqlType BIGINT */
          exception_value_eur: number;
        }>;
      };
    compliance_eligibility: {
        name: "compliance_eligibility";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType STRING */
          module_group: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType BOOLEAN */
          eligible_fastpick: boolean;
          /** @sqlType BOOLEAN */
          eligible_storepick: boolean;
        }>;
      };
    compliance_exceptions: {
        name: "compliance_exceptions";
        parameters: {
          /** STRING - use sql.string() */
          solution: SQLStringMarker;
          /** STRING - use sql.string() */
          family: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType STRING */
          module_group: string;
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          quantity: number;
          /** @sqlType BIGINT */
          sales_value_eur: number;
          /** @sqlType DATE */
          sales_date: string;
          /** @sqlType STRING */
          project_status: string;
        }>;
      };
    compliance_kpis: {
        name: "compliance_kpis";
        parameters: {
          /** STRING - use sql.string() */
          solution: SQLStringMarker;
          /** STRING - use sql.string() */
          family: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_modules: number;
          /** @sqlType BIGINT */
          exception_modules: number;
          /** @sqlType DECIMAL(27,2) */
          exception_rate: number;
          /** @sqlType BIGINT */
          affected_projects: number;
          /** @sqlType BIGINT */
          affected_customers: number;
          /** @sqlType BIGINT */
          exception_value_eur: number;
          /** @sqlType BIGINT */
          total_value_eur: number;
        }>;
      };
    filter_countries: {
        name: "filter_countries";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType BIGINT */
          module_rows: number;
        }>;
      };
    filter_families: {
        name: "filter_families";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          module_rows: number;
        }>;
      };
    filter_segments: {
        name: "filter_segments";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType BIGINT */
          customers: number;
        }>;
      };
    geo_country_solution: {
        name: "geo_country_solution";
        parameters: {
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType BIGINT */
          fastpick_projects: number;
          /** @sqlType BIGINT */
          storepick_projects: number;
          /** @sqlType BIGINT */
          total_projects: number;
          /** @sqlType DECIMAL(26,1) */
          fastpick_pct: number;
          /** @sqlType BIGINT */
          value_eur: number;
        }>;
      };
    geo_region_solution: {
        name: "geo_region_solution";
        parameters: {
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          region: string;
          /** @sqlType BIGINT */
          fastpick_projects: number;
          /** @sqlType BIGINT */
          storepick_projects: number;
          /** @sqlType BIGINT */
          total_projects: number;
          /** @sqlType DECIMAL(26,1) */
          fastpick_pct: number;
          /** @sqlType BIGINT */
          value_eur: number;
        }>;
      };
    geo_segment_solution: {
        name: "geo_segment_solution";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType BIGINT */
          fastpick_projects: number;
          /** @sqlType BIGINT */
          storepick_projects: number;
          /** @sqlType BIGINT */
          total_projects: number;
          /** @sqlType DECIMAL(26,1) */
          fastpick_pct: number;
          /** @sqlType BIGINT */
          value_eur: number;
        }>;
      };
    portfolio_kpis_metricview: {
        name: "portfolio_kpis_metricview";
        parameters: Record<string, never>;
        result: Array<{
          /** Sum of all module sales values in EUR */
          total_revenue_eur: number;
          /** Number of distinct projects */
          project_count: number;
          /** Number of distinct customers */
          customer_count: number;
          /** Total number of module sale line items */
          module_sales_count: number;
          /** Number of projects classified as strategic (total value > 20M EUR) */
          strategic_project_count: number;
          /** Percentage of projects using FASTPICK solution */
          fastpick_rate: number;
          /** Module installations where the module is now at T9 (no support given) - highest installed-base risk */
          t9_risk_count: number;
          /** Modules sold while T4 (current) that have since moved to T6 (end of sales) - installed-base lifecycle risk */
          t4_t6_risk_count: number;
          /** Module sales made when the module was already end-of-sales (T6) - indicates policy exception */
          t6_at_sale_count: number;
          /** Number of module sales that violate solution eligibility rules (incompatible with selected solution) */
          compatibility_exception_count: number;
          /** Average total project value including margin */
          avg_project_value_eur: number;
          /** Average module revenue per project (total sales divided by project count) */
          revenue_per_project_eur: number;
          /** Average number of module sales lines per project */
          modules_per_project: number;
        }>;
      };
    revenue_by_year_metricview: {
        name: "revenue_by_year_metricview";
        parameters: Record<string, never>;
        result: Array<{
          /** Year the project contract was signed */
          contract_year: number;
          /** Sum of all module sales values in EUR */
          total_revenue_eur: number;
          /** Number of distinct projects */
          project_count: number;
          /** Number of projects classified as strategic (total value > 20M EUR) */
          strategic_project_count: number;
        }>;
      };
    risk_by_customer: {
        name: "risk_by_customer";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType BIGINT */
          countries: number;
          /** @sqlType BIGINT */
          projects: number;
          /** @sqlType BIGINT */
          t9_modules: number;
          /** @sqlType BIGINT */
          t4_t6_modules: number;
          /** @sqlType BIGINT */
          exception_modules: number;
          /** @sqlType BIGINT */
          at_risk_value_eur: number;
        }>;
      };
    risk_by_family: {
        name: "risk_by_family";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          t9_modules: number;
          /** @sqlType BIGINT */
          t4_t6_modules: number;
          /** @sqlType BIGINT */
          t6_at_sale_modules: number;
        }>;
      };
    risk_kpis: {
        name: "risk_kpis";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_modules: number;
          /** @sqlType BIGINT */
          total_projects: number;
          /** @sqlType BIGINT */
          at_risk_modules: number;
          /** @sqlType BIGINT */
          t9_count: number;
          /** @sqlType BIGINT */
          t4_t6_count: number;
          /** @sqlType BIGINT */
          t6_at_sale_count: number;
          /** @sqlType BIGINT */
          exception_count: number;
          /** @sqlType BIGINT */
          t9_value_eur: number;
          /** @sqlType BIGINT */
          t4_t6_value_eur: number;
          /** @sqlType BIGINT */
          t9_customers: number;
          /** @sqlType BIGINT */
          t9_projects: number;
        }>;
      };
    t4t6_modules: {
        name: "t4t6_modules";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          quantity: number;
          /** @sqlType BIGINT */
          sales_value_eur: number;
          /** @sqlType DATE */
          sales_date: string;
        }>;
      };
    t6_at_sale_modules: {
        name: "t6_at_sale_modules";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          quantity: number;
          /** @sqlType BIGINT */
          sales_value_eur: number;
          /** @sqlType DATE */
          sales_date: string;
          /** @sqlType STRING */
          lifecycle_stage_current: string;
        }>;
      };
    t9_modules: {
        name: "t9_modules";
        parameters: {
          /** STRING - use sql.string() */
          country: SQLStringMarker;
          /** STRING - use sql.string() */
          segment: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_name: string;
          /** @sqlType STRING */
          customer_segment: string;
          /** @sqlType STRING */
          country: string;
          /** @sqlType STRING */
          region: string;
          /** @sqlType STRING */
          project_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          solution_name: string;
          /** @sqlType STRING */
          module_name: string;
          /** @sqlType STRING */
          product_family: string;
          /** @sqlType BIGINT */
          quantity: number;
          /** @sqlType BIGINT */
          sales_value_eur: number;
          /** @sqlType DATE */
          sales_date: string;
          /** @sqlType STRING */
          lifecycle_stage_at_sale: string;
        }>;
      };
  }
}
