// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import type {} from "@databricks/appkit-ui/react";
declare module "@databricks/appkit-ui/react" {
  interface MetricRegistry {}
}

export const metricViewsMetadata = {} as const;
